base_url = "https://zola-after-dark.netlify.com"
compile_sass = true
title = "after-dark theme"
description = ""
generate_feed = true

taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

[extra]
author = "Vincent"
after_dark_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
]
after_dark_title = "My blog"

# if favicon true
# we expect static to contain a favicon-32x32.png, favicon-16x16.png,
# site.webmanifest and apple-touch-icon.png
favicon = false